# Generated by Django 4.1.3 on 2022-12-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0002_torta_delete_tortas_rename_sinopsis_cafe_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
